auth-server: http://localhost:8080 # 认证服务器地址

server:
  port: 8085

security:
  oauth2:
    client:
      client-id: client1 # 授权服务器配置的client id
      client-secret: 123456 # 授权服务器配置的client secret
      scope: test
      access-token-uri: ${auth-server}/oauth/token # 获取access token接口
      user-authorization-uri: ${auth-server}/oauth/authorize #  获取Authorization Code接口
    resource:
      token-info-uri: ${auth-server}/oauth/check_token # 验证token的接口